version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password66
      POSTGRES_USER: user66
      POSTGRES_DB: db66
  app:
    image: my-node-app
    ports:
      - 13000:3000